export const define = {
    MIN_USERNAME_LENGTH: 3,
    MAX_USERNAME_LENGTH: 80,

    MIN_PASSWORD_LENGTH: 4,
    MAX_PASSWORD_LENGTH: 100,

    MIN_NICKNAME_LENGTH: 1,
    MAX_NICKNAME_LENGTH: 255,

    USER_ID_LENGTH: 20,
    REFRESH_TOKEN_ID_LENGTH: 35,
};